# -*- coding: utf-8 -*-
"""Healthcare: 235 industries. One concrete marketing fact each."""

H = {}

# --- Hospitals and facilities (20) ---
H["Hospitals"] = "Most hospital search traffic is people looking for a department, a wait time or parking, and the site is usually built around the org chart instead."
H["Teaching and academic hospitals"] = "Research reputation drives referrals and does nothing for the patient searching for an appointment, so the site has to serve both without one burying the other."
H["Children's hospitals"] = "Every search is made by a frightened parent, which makes plain answers about what happens next worth more than any reassurance about excellence."
H["Community and rural hospitals"] = "Competing against urban centres people will drive past you to reach, so the argument is access and wait time rather than capability."
H["Psychiatric hospitals"] = "Platform restrictions on mental health targeting are strictest here, which pushes almost the entire acquisition job into organic search and referral relationships."
H["Rehabilitation hospitals"] = "The referral comes from an acute hospital discharge planner, so the marketing audience is a professional with a caseload, not a patient."
H["Surgical and procedure centres"] = "Wait time is the product. Publishing a real number for how soon a procedure can be scheduled outperforms every other message tested."
H["Urgent care and walk-in clinics"] = "Current wait time is the single most searched piece of information about a walk-in clinic and almost nobody publishes it live."
H["After-hours and emergency clinics"] = "Demand peaks exactly when the phones are least staffed, so ad scheduling and an answered phone matter more than campaign structure."
H["Medical centres and multi-site groups"] = "Locations sharing a single set of campaigns bid against each other, and the group pays extra for the privilege."
H["Community health centres"] = "Funding models limit what can be promoted, so the marketing job is usually awareness of eligibility rather than acquisition."
H["Dialysis centres"] = "Patients attend three times a week for years, so proximity and chair availability decide the choice and nothing else comes close."
H["Infusion clinics"] = "Coverage and prior authorisation questions are the first thing patients ask and the last thing the website answers."
H["Sleep labs"] = "Most volume arrives by physician referral, and the growth lever is turnaround time to the referring doctor rather than consumer advertising."
H["Medical transport and ambulance"] = "Buyers are facilities and insurers on contract, so a strong consumer site is worth less than a page that survives a procurement review."
H["Vaccination and travel clinics"] = "Demand is trip-triggered and seasonal, and the search happens four to eight weeks before departure."
H["Occupational health clinics"] = "Sold to employers on turnaround time and compliance reporting, which means the buyer is an HR or safety manager."
H["Sexual health clinics"] = "Discretion is the conversion factor. Anonymous booking and clear privacy language do more than any messaging about care quality."
H["Plasma and blood donation centres"] = "Compensation and appointment convenience drive donor volume, and retention of existing donors is far cheaper than recruiting new ones."
H["Mobile clinics and health units"] = "Schedule and location change weekly, so the site's job is publishing where the unit will be, accurately and early."

# --- Senior and home care (12) ---
H["Long-term care"] = "Availability changes weekly and families rule out any provider whose website cannot tell them whether there is a bed."
H["Retirement and senior living"] = "Monthly cost is the first question, and communities that publish a starting range get more tours than ones that ask you to call."
H["Memory care"] = "The adult child searching is usually in crisis after an incident, and the decision window is days rather than months."
H["Home care agencies"] = "Hourly rate and minimum shift length are the two things every caller asks, and publishing them filters out the enquiries that were never going to book."
H["Caregiver and PSW agencies"] = "Recruitment and client acquisition compete for the same budget, and staffing is usually the binding constraint."
H["Adult day and respite programs"] = "Caregiver burnout drives the enquiry, so content that speaks to the caregiver converts better than content about the participant."
H["Hospice and palliative care"] = "Search happens at the hardest moment a family will face, and clear, calm information about what happens next matters more than any brand message."
H["Senior transportation"] = "Booking has to work by phone for the rider and online for the adult child arranging it, and most services only build one."
H["Medical alert and monitoring"] = "Bought by an adult child for a parent who did not ask for it, which means the creative has to overcome the parent's objection, not the buyer's."
H["Assisted and independent living"] = "Tours are the conversion event, and the gap between enquiry and booked tour is where most communities lose people."
H["Geriatric care management"] = "A service most families do not know exists, so the search volume is small and the content job is explaining the category."
H["Home accessibility and mobility fit-outs"] = "Triggered by a fall or a discharge, funded partly by grants, and the grant question is what the website needs to answer first."

# --- Medical and surgical specialties (40) ---
H["Family medicine and primary care"] = "Most practices are closed to new patients, so the marketing question is usually roster management rather than acquisition."
H["Concierge and direct primary care"] = "Selling an annual fee against free public care, which makes the entire argument about access and appointment length."
H["Cardiology"] = "Referral driven with a growing share of patients researching the cardiologist afterwards, and the biography page carries that decision."
H["Dermatology"] = "Medical and cosmetic dermatology need separate pages and separate campaigns because the buyers, budgets and platform rules are completely different."
H["Endocrinology and diabetes care"] = "GLP-1 demand has changed the search landscape entirely, and the compliance constraints on advertising it are tightening."
H["Gastroenterology"] = "Colonoscopy screening demand responds to age-based targeting better than almost any other procedure in medicine."
H["Hepatology"] = "Narrow, referral led, and the useful marketing asset is clear content for referring physicians rather than patients."
H["Neurology"] = "Long wait times are the category norm, so publishing a realistic one is a differentiator rather than an admission."
H["Neurosurgery"] = "Patients travel for the surgeon, which makes individual surgeon profiles and outcome context the highest value pages on the site."
H["Oncology"] = "Advertising is heavily restricted and any outcome claim is a serious risk, so the entire program runs on organic content and referral relationships."
H["Hematology"] = "Small patient populations and physician-driven referral, so search volume is low and the content should be written for clinicians."
H["Infectious disease"] = "Demand is event driven and unpredictable, which makes standing organic content far more valuable than campaigns."
H["Geriatrics"] = "The adult child is doing the searching, and content addressed to them converts better than content addressed to the patient."
H["OB-GYN and women's health"] = "Patients choose a provider they expect to see for years, so the practitioner biography does more work than the practice description."
H["Fertility and IVF"] = "Cost and success rates are the two questions, both are regulated in how they can be presented, and firms that publish clear pricing get more consultations."
H["Pediatrics"] = "Parents choose on availability and how quickly a sick child can be seen, not on philosophy of care."
H["Psychiatry"] = "Wait times of several months are normal, and publishing yours honestly keeps enquiries warm instead of losing them to a competitor who did."
H["Pulmonology and respirology"] = "Sleep apnea and CPAP demand behaves like a consumer category while the rest of the practice is referral driven."
H["Rheumatology"] = "Long diagnostic journeys mean patients arrive having already researched extensively, so content has to be more specific than the usual overview."
H["Nephrology"] = "Almost entirely referral driven, and the marketing that matters is communication quality back to the referring physician."
H["Urology"] = "Men delay seeking care for years, and discreet, direct content about specific symptoms outperforms general practice messaging."
H["ENT and otolaryngology"] = "Split between routine referral work and elective procedures like septoplasty that behave like cosmetic purchases."
H["Allergy and immunology"] = "Sharply seasonal search demand that spikes with pollen counts and collapses between seasons."
H["Sports medicine"] = "Athletes and active patients research the practitioner, and association with a team or club carries more weight than any credential list."
H["Pain management"] = "Advertising restrictions around opioids and pain treatment are significant, and copy has to describe assessment rather than relief."
H["Sleep medicine"] = "Patients arrive already suspecting the diagnosis, so content that explains the study process and cost converts better than symptom awareness content."
H["CPAP and sleep apnea clinics"] = "Equipment sales and clinical service have different economics, and blending them in the reporting hides which one is working."
H["Bariatric and weight medicine"] = "The most heavily restricted advertising category in healthcare, where before and after imagery and outcome claims are both prohibited."
H["Vein and vascular clinics"] = "Cosmetic and medical vein treatment sit under different insurance and advertising rules, and mixing them on one page satisfies neither."
H["Thoracic surgery"] = "Referral driven and surgeon specific, where the useful asset is a credible profile rather than a service page."
H["Colorectal surgery"] = "Screening awareness drives volume, and age-targeted campaigns perform where general awareness campaigns do not."
H["Transplant programs"] = "Referral relationships with regional centres carry the volume, and outcome data is published under strict reporting rules."
H["Orthopedics"] = "Joint replacement wait times drive patients to travel, and publishing a realistic surgical date wins consultations."
H["Hand and upper limb clinics"] = "Workplace injury and insurance referral drive much of the volume, so the audience includes adjusters and case managers."
H["Plastic and cosmetic surgery"] = "Before and after imagery is restricted on the platforms that drive the category, which forces the creative onto process, credentials and consultation."
H["Wound care clinics"] = "Referral from home care and long-term care providers, with turnaround and reporting quality as the selling points."
H["Hyperbaric oxygen therapy"] = "Approved indications are narrow and claims beyond them attract regulatory attention quickly."
H["Lymphedema clinics"] = "Small patient population, high loyalty, and coverage questions dominating every first conversation."
H["Genetics and genomic testing"] = "Direct to consumer and clinical testing face different rules, and conflating them in marketing creates a compliance problem."
H["Medico-legal and IME providers"] = "The buyers are lawyers and insurers, so the site is a business to business asset and consumer messaging is wasted."

# --- Maternal and newborn care (6) ---
H["Maternity and prenatal clinics"] = "The decision window opens with a positive test and closes at delivery, which is one of the few genuinely predictable timelines in healthcare."
H["Birth centres"] = "Competing against free hospital birth, so the argument is experience and continuity rather than safety, which cannot be claimed comparatively."
H["Prenatal imaging and 3D ultrasound"] = "A discretionary, gift-like purchase with a narrow gestational window, which makes timing the targeting the whole job."
H["Maternal and perinatal mental health"] = "Platform restrictions on mental health targeting apply fully, and the audience is reached through partner referral more reliably than through ads."
H["Midwifery and doulas"] = "Chosen through local parent communities and word of mouth, where reviews and recommendations outweigh any advertising."
H["Lactation and postpartum support"] = "Urgent need in the first two weeks after birth, so same-day availability is the message that converts."

# --- Pediatric and child health (6) ---
H["Pediatric centres and children's clinics"] = "Parents choose on how fast a sick child can be seen, and publishing same-day availability beats every other message."
H["Pediatric urgent care"] = "Peak demand is evenings and weekends, and campaigns scheduled for business hours miss most of it."
H["Children's therapy centres"] = "Waitlists run months, and the practices that publish honest wait times keep families who come back when a space opens."
H["Child development and assessment centres"] = "Assessment cost and whether it is covered are the deciding questions, and most sites answer neither."
H["Child and youth mental health"] = "Targeting restrictions are absolute here, so all reach comes through parent-directed content and school or physician referral."
H["Children's vision and optometry"] = "School vision screening failures drive the enquiry, which makes the back-to-school window disproportionately valuable."

# --- Dental (12) ---
H["General dentistry"] = "Insurance acceptance is the first filter for most patients, and practices that list their accepted plans get more calls than ones that say they accept most."
H["Cosmetic dentistry and veneers"] = "A considered purchase researched for months, where financing availability moves more consultations than price reductions."
H["Orthodontics and aligners"] = "Competing against direct to consumer aligner brands on price, which makes supervised treatment and included refinements the argument."
H["Periodontics and implants"] = "High ticket, referral led, and the patient usually needs the cost explained in a way the referring dentist did not."
H["Endodontics"] = "Almost entirely referral driven and urgent, so availability communicated to referring practices matters more than consumer advertising."
H["Oral and maxillofacial surgery"] = "Wisdom teeth demand is seasonal around school breaks, and the rest of the practice runs on specialist referral."
H["Pediatric dentistry"] = "Parents choose on how the practice handles an anxious child, and content showing that is worth more than clinical credentials."
H["Sedation and emergency dentistry"] = "Emergency searches happen at night and on weekends, and paying for those clicks without an answered phone is pure waste."
H["Dental sleep medicine"] = "A crossover category where the patient found you through a sleep search, so the content has to bridge two vocabularies."
H["Denturists"] = "An older patient base that still prefers phone contact, which makes a prominent phone number and call tracking more important than form optimisation."
H["Dental hygiene clinics"] = "An independent model many patients do not know exists, so the content job is explaining the category before selling the practice."
H["Dental groups and DSOs"] = "Location pages that differ only by city name rank badly, and most groups have dozens of them."

# --- Eye and vision (8) ---
H["Optometry"] = "Competing with retail chains on exam price, where insurance clarity and appointment availability win more bookings than eyewear selection."
H["Ophthalmology"] = "Referral driven for medical work and consumer driven for elective surgery, which needs two different sets of pages."
H["LASIK and refractive surgery"] = "Headline prices are usually per eye and exclude aftercare, and buyers have learned to distrust them, so publishing the full cost is a differentiator."
H["Cataract surgery"] = "Public wait times drive patients toward private options, and the honest comparison of wait and cost is the content that converts."
H["Retina clinics"] = "Urgent referral from optometrists, so the relationship and turnaround time to those practices is the growth channel."
H["Dry eye clinics"] = "Patients arrive after years of failed self-treatment, so content that explains why previous attempts did not work outperforms service descriptions."
H["Vision therapy and low vision"] = "Parents and adult children searching on behalf of someone else, and the category needs explaining before the practice does."
H["Opticians and eyewear retail"] = "Online eyewear competes on price and return policy, so in-person fitting and adjustment is the argument that holds."

# --- Hearing (3) ---
H["Audiology and hearing clinics"] = "The free hearing test is the conversion event, because it is the low commitment step someone in denial will actually take."
H["Hearing aid retail groups"] = "Device pricing is publicly compared and commoditising, so the durable position is the fitting and the follow-up care."
H["Tinnitus clinics"] = "Sufferers search obsessively and have usually been told nothing can be done, which makes honest content about what management involves unusually effective."

# --- Allied health and rehab (15) ---
H["Physiotherapy"] = "Direct billing to insurers is the deciding factor for most bookings and it belongs on the page, not in a phone call."
H["Pelvic health physiotherapy"] = "A sensitive category with high demand and low awareness, where discreet, specific content outperforms general clinic marketing."
H["Concussion and vestibular rehab"] = "Referral from sport organisations and physicians, with return-to-play protocols as the content that establishes credibility."
H["Chiropractic"] = "A crowded local category where new patient offers have trained the market to shop, and clinics competing on availability hold better margins."
H["Registered massage therapy"] = "Booked around insurance coverage limits, which makes remaining-benefit reminders near year end unusually effective."
H["Occupational therapy"] = "Funded through insurers, workplace claims and home care contracts, so the buyer is frequently a case manager rather than a patient."
H["Speech-language pathology"] = "Parents searching after a school or physician flag, with waitlist length as the deciding factor between clinics."
H["Kinesiology and athletic therapy"] = "Often not covered by insurance, which means the value has to be explained rather than assumed."
H["Naturopathic medicine"] = "Advertising claims are tightly constrained by regulatory colleges, and describing the assessment process is safer and more effective than describing outcomes."
H["Osteopathy"] = "Regulatory status and coverage vary by province and state, which changes both the messaging and what can be claimed."
H["Acupuncture and TCM"] = "Coverage questions dominate the first call, and clinics that publish which insurers they bill directly book more first visits."
H["Dietitians and clinical nutrition"] = "Registered dietitians compete for search visibility with unregulated nutrition advice, so credentials need to be prominent and explained."
H["Podiatry and chiropody"] = "Custom orthotics carry the margin and coverage questions drive the booking, so the two need to be answered together."
H["Orthotics and prosthetics"] = "Long-term patient relationships funded through insurance and public programs, where the funding pathway is the content that matters."
H["Multidisciplinary rehab clinics"] = "Motor vehicle accident and workplace claim work brings a referral audience of adjusters and lawyers alongside patients."

# --- Mental and behavioural health (11) ---
H["Psychology"] = "Session cost and coverage are the first questions, and practices that publish their rate get fewer calls and more bookings."
H["Counselling and therapy practices"] = "Matching a client to the right therapist inside the practice is where most enquiries are lost, not at the ad."
H["Group and multi-clinician practices"] = "Individual therapist profiles with real specialisation detail convert better than any practice-level page."
H["Addiction and recovery centres"] = "Advertising is restricted and, in the United States, subject to certification requirements for treatment providers."
H["Eating disorder programs"] = "Platform policy prohibits most weight and body imagery, which removes the obvious creative approach entirely."
H["Ketamine and TMS clinics"] = "New treatment categories where patients arrive uncertain what is legitimate, so evidence and physician oversight are the content."
H["Autism services and ABA therapy"] = "Funding pathways differ by province and state, and the funding question is what parents are actually searching."
H["Behavioural health networks"] = "Multi-site operations where clinician availability by location changes weekly and the website almost never reflects it."
H["Employee assistance providers"] = "Sold to HR leaders on utilisation and reporting, so it is a business to business program with a consumer-facing surface."
H["Telehealth and virtual care"] = "Licensing is jurisdictional, so advertising has to be geographically constrained to where the clinicians can legally practise."
H["Digital mental health apps"] = "App store economics and health claims restrictions collide, which limits what performance creative can say."

# --- Aesthetics and med spa (9) ---
H["Med spas"] = "Membership and treatment plans hold margin where single-session discounting destroys it, and the difference shows within two quarters."
H["Injectables and botox clinics"] = "Per-unit pricing is compared openly, and clinics competing on price alone lose clients to whoever discounts next."
H["Laser and skin clinics"] = "Device brand names carry real search volume, and pages built around the specific technology outrank general treatment pages."
H["Body contouring"] = "Meta prohibits ads implying negative self-perception about appearance, which rules out most of the copy this category defaults to."
H["Hair restoration and transplant"] = "Results imagery is restricted, so surgeon credentials, technique explanation and consultation process carry the decision."
H["Tattoo removal"] = "Session count and total cost are the questions, and clinics that publish a realistic range get better qualified consultations."
H["Teeth whitening studios"] = "Competing against at-home kits on price, so the argument is supervised results and speed rather than cost."
H["Permanent makeup and lash studios"] = "Artist-led rather than brand-led, where the individual technician's portfolio drives bookings."
H["Medical aesthetics training"] = "The buyer is a practitioner making a career investment, so the content is about certification, earning potential and course logistics."

# --- Wellness and longevity (10) ---
H["IV therapy"] = "Claims about benefits are the compliance risk, and clinics that describe the protocol rather than the outcome clear review reliably."
H["Hormone therapy and men's health"] = "Heavily restricted advertising with rising enforcement, where the safe position is describing testing and physician oversight."
H["Menopause and midlife care"] = "Underserved demand with high search volume and very little quality content, which makes organic search unusually winnable."
H["Weight loss and GLP-1 programs"] = "The most scrutinised advertising category in healthcare right now, with restrictions tightening across every platform."
H["Preventative and longevity clinics"] = "Self-pay programs at high price points where publishing what is included and what it costs is the entire differentiator."
H["Integrative and functional medicine"] = "Testing panels and protocol detail are what prospective patients compare, and vague wellness language loses to specifics."
H["Wellness clinics"] = "A broad label that means nothing to a searcher, so the pages that work are built around the specific service rather than the category."
H["Cryotherapy and recovery studios"] = "Membership economics decide the business, so the marketing goal is the trial that converts to a recurring plan."
H["Sauna and float studios"] = "Local, experiential and membership driven, where first visit conversion to membership is the only metric that matters."
H["Sexual wellness clinics"] = "Discretion drives the format, and anonymous enquiry options convert substantially better than standard contact forms."

# --- Animal health (11) ---
H["Veterinary clinics"] = "Many practices are at capacity and closed to new patients, which makes recruitment marketing more valuable than acquisition."
H["Animal hospitals and emergency vet"] = "Emergency searches happen overnight, and publishing the current wait time and intake status prevents wasted trips and the bad reviews that follow them."
H["Veterinary specialty and referral"] = "The audience is referring general practice vets, so the marketing is business to business and the content is clinical."
H["Mobile and house-call vets"] = "Service area accuracy is the whole campaign, because a booking outside the radius costs an hour of unpaid driving."
H["Equine and large animal vets"] = "Rural, relationship driven and low search volume, where a well-built page can own the category in a region outright."
H["Exotic and avian vets"] = "Owners travel long distances for species-specific expertise, so the pages should be built per species rather than per service."
H["Veterinary dentistry"] = "Owners do not know the service exists until a vet raises it, which makes the content job education rather than acquisition."
H["Pet wellness and grooming"] = "Recurring appointments where booking convenience and consistency of groomer decide retention."
H["Pet boarding and daycare"] = "Demand spikes around holidays and the booking happens weeks ahead, so campaign timing is the main lever."
H["Pet insurance"] = "A comparison-shopped financial product where exclusions and waiting periods are what buyers actually compare."
H["Pet telehealth"] = "Licensing rules restrict what can be diagnosed remotely, which varies by jurisdiction and constrains the advertising claim."

# --- Pharmacy, labs and diagnostics (8) ---
H["Pharmacies"] = "Competing with chains on hours and location, where services like injections and medication reviews are the differentiator worth advertising."
H["Compounding pharmacies"] = "Prescriber relationships drive volume, so the marketing audience is physicians and veterinarians rather than patients."
H["Specialty and infusion pharmacy"] = "Payer contracts and clinic relationships decide the business, and consumer marketing has almost no role."
H["Online and DTC pharmacy"] = "Prescription advertising rules differ sharply between Canada and the United States, and getting it wrong is a licensing problem."
H["Medical laboratories"] = "Turnaround time and report clarity are what referring clinicians choose on, and neither is usually on the website."
H["Diagnostic imaging and radiology"] = "Public wait times push patients toward private imaging, and publishing your next available appointment is the strongest message available."
H["Dental and medical labs"] = "Business to business with practices as clients, where case turnaround and remake rates are the buying criteria."
H["At-home and consumer testing"] = "Regulated as both a health service and a consumer product, and the claims permitted are narrower than most brands assume."

# --- Healthcare business and tech (19) ---
H["Healthcare generally"] = "A category term with high volume and almost no buying intent, which makes it a poor place to spend and a reasonable place to rank."
H["Clinics generally"] = "Searchers using this term are early in research, so the useful response is orientation content rather than a service pitch."
H["Doctors and physicians"] = "Physicians buying for their own practice behave like small business owners, not like the healthcare enterprise buyer."
H["Health tech and clinical software"] = "Security and compliance documentation gets requested in every deal, and publishing it openly removes weeks from the cycle."
H["Practice management and EMR"] = "Switching costs are enormous, so the marketing job is reaching practices in the narrow window when they are already unhappy."
H["Patient engagement platforms"] = "Sold on staff time saved rather than patient experience, because the buyer is the person doing the administrative work."
H["Medical billing and RCM"] = "Buyers compare on collection rate and days in accounts receivable, which are the only numbers worth putting on the page."
H["Medical coding and credentialing"] = "A compliance purchase where accuracy and audit defensibility matter more than price or speed."
H["Healthcare staffing and recruiting"] = "Two audiences, clinicians and facilities, and the constraint moves between them with the labour market."
H["Medical answering and reception"] = "Sold on missed call recovery, which is a number the prospect can be shown from their own data."
H["Clinical trials and research sites"] = "Patient recruitment advertising is regulated and requires ethics board approval before it runs."
H["Contract research organisations"] = "Long procurement cycles with sponsors, where published capability and therapeutic area experience carry the shortlist."
H["Health insurance and benefits"] = "Sold to employers on cost containment and to members on access, which are different messages entirely."
H["Disability and injury management"] = "Insurers and employers are the buyers, and outcome data on return to work is what they compare."
H["Healthcare franchises and MSOs"] = "Franchise recruitment and patient acquisition are separate programs that get funded from one budget and should not."
H["Practice brokerage and transitions"] = "A once-in-a-career transaction for the seller, so the content job is explaining valuation and process long before the sale."
H["Medical education and training"] = "Continuing education requirements create predictable annual demand tied to licensing cycles."
H["Healthcare non-profits"] = "Donor acquisition and service awareness compete for budget, and grant restrictions often limit what can be spent on either."
H["Healthcare consulting firms"] = "Sold on named partner expertise, so individual consultant profiles outperform firm capability pages."

# --- Healthcare ecommerce and brands (45) ---
H["Healthcare ecommerce"] = "Health claims restrict what creative can test, which narrows the usual DTC playbook before the first ad is written."
H["Medical devices"] = "Regulatory clearance status determines what can be claimed, and marketing ahead of clearance is a serious compliance exposure."
H["Medical supplies"] = "Bought on price and availability by procurement, so the site is a catalogue that has to be searchable rather than persuasive."
H["Durable medical equipment"] = "Insurance and funding eligibility is the first question, and brands that explain the coverage pathway convert better."
H["Mobility equipment"] = "The buyer is often an adult child or occupational therapist rather than the user, which changes the entire message."
H["Surgical instruments"] = "Business to business with hospital procurement, where certifications and sterilisation compatibility are the specifications that matter."
H["Medical imaging equipment"] = "Long capital cycles and committee purchases where the marketing supports a champion inside the organisation."
H["Sterilisation and infection control"] = "Compliance driven purchasing where standards conformity is the specification buyers filter on."
H["Dental supplies"] = "Practices reorder consistently, which makes the acquisition cost recoverable over years and subscription models unusually viable."
H["Veterinary supplies and pet pharmacy"] = "Split between clinic wholesale and consumer sales, which are different businesses with different margins."
H["Hearing aid brands"] = "Direct to consumer models compete against clinic fitting, and the argument is support rather than device specification."
H["Contact lens and eyewear ecommerce"] = "Prescription verification requirements add friction that has to be designed around rather than removed."
H["Clear aligner brands"] = "Regulatory scrutiny over remote treatment supervision has reshaped what this category is permitted to claim."
H["Supplements and vitamins"] = "Repeat purchase economics decide the business, and brands that do not model the third order do not know what they can pay for a customer."
H["Nutraceuticals"] = "Structure and function claims are permitted, disease claims are not, and the line between them is where enforcement happens."
H["Skincare and cosmeceuticals"] = "Clinical-sounding language invites regulatory attention, and ingredient specificity performs better anyway."
H["At-home therapy devices"] = "Device claims require evidence and the platforms reject aggressively, so the creative sells the routine rather than the result."
H["Health wearables"] = "Health claims turn a consumer device into a regulated one, which is a line marketing teams cross accidentally."
H["CPAP and sleep supplies"] = "A replacement cycle business with predictable consumable reorder timing, which makes replenishment flows the main revenue lever."
H["Diabetic supplies"] = "Insurance coverage and reorder convenience decide loyalty far more than price."
H["Wound care and ostomy supplies"] = "Discreet delivery and sample availability matter more to buyers than any product messaging."
H["Incontinence supplies"] = "Discretion is the product, and packaging and delivery language do more for conversion than anything on the ad."
H["Compression and recovery wear"] = "Split between medical necessity and athletic performance, which are two audiences that should never share a landing page."
H["Orthopedic braces and supports"] = "Fit and sizing uncertainty drives returns, so measurement guidance is the highest value page on the site."
H["Orthopedic footwear and insoles"] = "Coverage under extended health plans drives purchases, and explaining the claim process lifts conversion."
H["Maternity and baby health"] = "A short customer window that closes fast, so range extension is the only route to repeat purchase."
H["Fertility products"] = "Emotionally charged with strict limits on outcome claims, where community trust outweighs advertising."
H["Sexual wellness products"] = "Platform advertising restrictions are severe, which pushes the category toward organic search, email and creator content."
H["Scrubs and medical uniforms"] = "Bought by individuals and by institutions on contract, and the two need different pricing and different pages."
H["PPE and first aid"] = "Demand is compliance driven for businesses and event driven for consumers, which makes forecasting difficult."
H["Clinic furniture and equipment"] = "Considered capital purchases where lead time and installation support are the deciding factors."
H["Lab supplies and consumables"] = "Recurring institutional purchasing where catalogue search and reorder speed beat any marketing message."
H["Sports nutrition and protein"] = "A crowded category where third party testing certification is the credibility signal that actually differentiates."
H["Probiotics and gut health"] = "Strain specificity and clinical evidence are what informed buyers compare, and vague gut health language loses to them."
H["Herbal and botanical remedies"] = "Traditional use claims are permitted in some markets and not others, which changes the copy by jurisdiction."
H["Medical foods and clinical nutrition"] = "A regulated category requiring physician supervision, which limits direct to consumer advertising sharply."
H["Infant formula and baby nutrition"] = "Marketing is restricted by international codes and national law, and enforcement in this category is unusually strict."
H["Sleep and recovery supplements"] = "Sleep claims sit close to the drug claim boundary, and crossing it is the most common rejection in the category."
H["Pet supplements and nutrition"] = "Veterinary claims are regulated separately from human supplements and the permitted language is narrower."
H["Home diagnostics and monitors"] = "Accuracy claims require substantiation and comparison against clinical measurement is closely scrutinised."
H["Respiratory devices and nebulisers"] = "Prescription requirements vary by device and jurisdiction, which determines whether direct sale is even possible."
H["Pain relief and TENS devices"] = "Pain relief claims are restricted and the compliant position describes the mechanism rather than the outcome."
H["Oral care and whitening products"] = "Whitening claims and abrasion safety are both regulated, and clinical comparison claims need substantiation."
H["Menstrual and period care"] = "Subscription economics work well here, and material safety and ingredient transparency are what buyers compare."
H["Medical ID and safety products"] = "Bought after an incident or a diagnosis, so the search is specific and the intent is unusually high."
