# -*- coding: utf-8 -*-
"""Professional Services: 120 industries. One concrete marketing fact each."""

P = {}

# --- Legal services (16) ---
P["Personal injury law firms"] = "Among the most expensive keywords in advertising, where the first firm to make contact signs a disproportionate share of matters."
P["Medical malpractice law firms"] = "Long, expensive matters with heavy screening, so the marketing job is filtering rather than generating volume."
P["Employment law firms"] = "Employee and employer work require separate positioning, and running both from one site creates a conflict problem in the buyer's mind."
P["Family law firms"] = "People search at their worst moment and choose on approachability, so fee transparency and process clarity outperform credential lists."
P["Criminal defence law firms"] = "Urgent, often searched at night or from a police station, which makes twenty four hour answering the deciding factor."
P["Immigration law firms"] = "Policy changes create sudden search spikes, and firms that publish accurate updates capture them."
P["Corporate law firms"] = "Relationship and referral driven, where individual partner reputation carries far more weight than the firm's site."
P["Commercial litigation firms"] = "In-house counsel research the individual litigator, so partner profiles with real matter experience are the money pages."
P["Real estate law firms"] = "Volume driven with fee competition, where turnaround time and closing reliability are what agents refer on."
P["Estate planning law firms"] = "Life events trigger the search, and content explaining what happens without a will converts better than service descriptions."
P["Tax law firms"] = "Triggered by an audit or a notice, which makes the search urgent, specific and high intent."
P["Class action law firms"] = "Campaign-specific and time-bound, where speed to build a claimant landing page decides participation."
P["Disability law firms"] = "Claimants have usually been denied once already, so content about the appeal process is what they are searching."
P["Insurance defence firms"] = "Insurers are the client, which makes this a business to business panel relationship rather than a consumer practice."
P["Intellectual property law firms"] = "Technical specialisation by field is what clients filter on, and generalist IP positioning loses to it."
P["Multi-office law firms"] = "Offices with near-identical pages compete against each other, and most multi-office firms have exactly that."

# --- Financial services (17) ---
P["Financial advisory firms"] = "Fee structure is what prospective clients most want to know and what almost no firm publishes."
P["Wealth management firms"] = "Minimum investment thresholds should be stated, because unqualified enquiries consume advisor time that cannot be recovered."
P["Investment management firms"] = "Performance claims are restricted by securities regulators, and marketing needs compliance sign-off before publishing."
P["Private wealth firms"] = "Referral and relationship driven, where the website's job is confirming credibility rather than generating leads."
P["Mortgage brokerages"] = "Rate driven search where speed of response decides the application, and rates change often enough to make static pages a liability."
P["Mortgage lenders"] = "Rate comparison sites dominate the search results, which pushes lenders toward broker relationships and brand."
P["Credit unions"] = "Membership eligibility is the first filter and it is frequently unclear on the site."
P["Community banks"] = "Local presence is the differentiator against national institutions, and branch-level content is how it gets expressed."
P["Commercial lenders"] = "Business borrowers compare terms and speed to funding, which are the two things worth publishing."
P["Fintech companies"] = "Regulatory positioning determines what can be claimed and it changes by jurisdiction."
P["Payments companies"] = "Pricing transparency is a differentiator in a category built on obscured fee structures."
P["Foreign exchange companies"] = "Rate and fee comparison drives the decision, and hidden margin in the spread is the industry norm buyers have learned to check."
P["Consumer finance companies"] = "Lending advertising is regulated with mandatory disclosure requirements on rates and terms."
P["Equipment finance companies"] = "Sold through vendor and dealer relationships, which makes the partner channel the growth priority."
P["Private equity firms"] = "Marketing serves deal flow and limited partner relations, which are entirely different audiences."
P["Venture capital firms"] = "Founders choose investors on reputation and portfolio, so the partner content is the marketing."
P["Family offices"] = "Discretion is the norm, and most do not market at all, which makes visibility itself a positioning decision."

# --- Insurance (11) ---
P["Insurance brokerages"] = "Personal lines is a price comparison fight while commercial is relationship driven, and one site usually serves neither well."
P["Commercial insurance brokerages"] = "Industry specialisation is what buyers filter on, and a page per industry outperforms a general commercial page."
P["Personal insurance brokerages"] = "Aggregators dominate the search results, so brokers compete on advice and claims support rather than quote speed."
P["Employee benefits firms"] = "HR leaders buy on plan design and administrative burden, and the monthly cost comes third."
P["Life insurance agencies"] = "Life events trigger the search, and needs-based content converts better than product comparison."
P["Health insurance agencies"] = "Enrolment periods concentrate demand into a few weeks, which makes campaign timing the main lever."
P["Property and casualty agencies"] = "Renewal timing drives switching, and campaigns aligned to renewal months outperform continuous spend."
P["Specialty insurance firms"] = "Narrow niches with low search volume where a well-built page can own the category outright."
P["Managing general agencies"] = "Brokers are the customer, which makes this business to business distribution rather than consumer insurance."
P["Insurtech companies"] = "Regulatory licensing by jurisdiction determines where the product can be advertised at all."
P["Multi-office insurance firms"] = "Local presence and licensing vary by office, and the site has to reflect both accurately."

# --- Accounting and tax (11) ---
P["Accounting firms"] = "Compliance work is commoditising and advisory is where growth is, but most firms market the compliance."
P["CPA firms"] = "Designation rules limit how specialisation can be described, and the permitted language varies by professional body."
P["Bookkeeping firms"] = "Software has compressed pricing, so the position has to be advisory support rather than data entry."
P["Tax advisory firms"] = "Seasonal search spikes around filing deadlines with a long quiet period that advisory content should fill."
P["Corporate tax firms"] = "Sold to finance leaders on risk reduction and planning, which are different messages from consumer tax."
P["Forensic accounting firms"] = "Lawyers and insurers are the referral source, so the marketing audience is professional rather than commercial."
P["Fractional CFO firms"] = "A growing category that many buyers do not know exists, so content has to explain the model first."
P["Payroll service firms"] = "Compliance accuracy and support responsiveness are the buying criteria, and price is a distant third."
P["Audit firms"] = "Independence rules restrict what can be marketed and to whom, and getting it wrong is a regulatory issue."
P["Valuation firms"] = "Triggered by a transaction, dispute or estate, which makes the search event driven and specific."
P["Insolvency and restructuring firms"] = "People search in distress and often anonymously, which makes discreet enquiry options important."

# --- Consulting and advisory (14) ---
P["Management consulting firms"] = "Buyers hire the named consultant, so individual profiles outperform firm capability pages consistently."
P["Strategy consulting firms"] = "Published thinking is the credential, and firms without a point of view compete on price."
P["Operations consulting firms"] = "Sold on measurable improvement, which means published outcomes matter more than methodology descriptions."
P["HR consulting firms"] = "Regulatory change creates urgent demand spikes that content published quickly can capture."
P["Marketing consulting firms"] = "Selling marketing means the firm's own marketing is the proof, and buyers check."
P["Technology consulting firms"] = "Vendor certifications are what buyers filter on, and each one deserves its own page."
P["Cybersecurity consulting firms"] = "Incidents drive urgent demand, and standing content ranks when the search happens."
P["Sustainability consulting firms"] = "Reporting requirements create compliance driven demand tied to regulatory deadlines."
P["Healthcare consulting firms"] = "Sector-specific credibility is the entry requirement, and generalist positioning does not clear it."
P["Government relations firms"] = "Registration and lobbying disclosure rules constrain how services can be described publicly."
P["Economic consulting firms"] = "Litigation support and policy work have different buyers, and expert witness credentials are the qualification."
P["Procurement consulting firms"] = "Sold on measurable savings, so the case for the engagement is arithmetic and should be shown as such."
P["Business brokerage firms"] = "Sellers search once in a career, so the content job is explaining valuation and process years before the sale."
P["Mergers and acquisitions advisors"] = "Deal experience by sector and size is what clients filter on, and a transaction list is the credential."

# --- Technology and managed services (12) ---
P["Managed IT service providers"] = "Contract value over years justifies an acquisition cost that looks indefensible against a first month invoice."
P["Cybersecurity companies"] = "Compliance requirements drive purchasing, and mapping services to specific frameworks is what buyers search."
P["Cloud consulting firms"] = "Platform partnership tiers are the credential buyers filter on, and each partnership deserves a page."
P["Software development companies"] = "Portfolio and technical depth carry the decision, and offshore price competition makes process the differentiator."
P["Data and analytics consultancies"] = "Buyers want to see the deliverable, so sample outputs do more than capability descriptions."
P["ERP consulting firms"] = "Implementation partner selection follows platform selection, so the marketing has to reach buyers at the right stage."
P["CRM consulting firms"] = "Adoption failure is the buyer's real fear, and addressing it directly differentiates from implementation-focused competitors."
P["Telecommunications companies"] = "Business contracts with long terms where service level agreements decide the purchase."
P["IT asset disposition companies"] = "Data destruction certification and environmental compliance are the qualifying criteria."
P["Digital transformation consultancies"] = "A vague category label, so the pages that work are built around specific outcomes rather than the term."
P["AI consulting firms"] = "A fast-moving category where demonstrated implementations matter more than claimed capability."
P["B2B SaaS companies"] = "Free trial and demo paths need separate measurement because they attract different buyer readiness."

# --- Real estate and property (11) ---
P["Commercial real estate brokerages"] = "Listings drive search traffic and the brokers are the actual product, which is a tension most sites never resolve."
P["Residential real estate brokerages"] = "Individual agents market against their own brokerage, which splits budget and confuses the brand."
P["Property management companies"] = "Owners buy on reporting transparency and tenant retention, not on management fee percentage."
P["Commercial property management firms"] = "Institutional owners require reporting and compliance capability that should be documented publicly."
P["Real estate investment firms"] = "Securities regulations restrict how investment opportunities can be advertised and to whom."
P["Real estate development firms"] = "Pre-sales and investor confidence are the marketing objectives, not consumer awareness."
P["Architecture firms"] = "Selected on portfolio and project type experience, which makes the project pages the entire marketing asset."
P["Engineering firms"] = "Professional designation is legally protected and describing capability incorrectly is a regulatory issue."
P["Surveying firms"] = "Transaction and construction driven, where turnaround time is the deciding factor between firms."
P["Appraisal firms"] = "Lenders and lawyers are the referral source, so turnaround time and report acceptance are the selling points."
P["Mortgage appraisal companies"] = "Lender panel membership drives the volume, which makes this a business to business relationship business."

# --- Recruitment and people services (9) ---
P["Recruitment agencies"] = "Two audiences with one budget, and the constraint moves between candidates and clients with the labour market."
P["Executive search firms"] = "Confidentiality limits what can be published, so the marketing is partner reputation and sector track record."
P["Staffing agencies"] = "Candidate supply is usually the binding constraint, and most agencies still market only to employers."
P["Healthcare staffing firms"] = "Credential verification and compliance are the operational differentiators worth marketing."
P["Technology staffing firms"] = "Technical screening quality is what clients pay for, and describing the process is the sale."
P["Professional employer organizations"] = "Compliance and benefits access are the buying reasons, and cost comparison against in-house HR is the proof."
P["Employer of record companies"] = "Country coverage and compliance depth are what buyers filter on before anything else."
P["Training companies"] = "Certification and accreditation drive enrolment, and each credential deserves its own page."
P["Leadership development firms"] = "Sold to HR and executive buyers on measurable behaviour change, which needs evidence rather than assertion."

# --- Professional and regulated services (11) ---
P["Engineering consultancies"] = "Discipline-specific expertise is what clients search, and one page per discipline outperforms a combined capabilities page."
P["Environmental consultancies"] = "Regulatory compliance deadlines drive predictable demand, and permitting expertise is the differentiator."
P["Scientific consulting firms"] = "Expert credentials and publications are the credential, and named scientist profiles carry the decision."
P["Compliance consulting firms"] = "Framework-specific expertise is what buyers filter on, so pages map to standards rather than services."
P["Quality assurance consultancies"] = "Certification standards define the market, and each standard is its own search term."
P["Translation companies"] = "Language pairs and subject specialisation are the filters, and certification requirements vary by document type."
P["Corporate investigation firms"] = "Discretion is the product, and licensing requirements vary significantly by jurisdiction."
P["Security consulting firms"] = "Clearances and certifications qualify the firm before any conversation begins."
P["Government contractors"] = "Procurement vehicles and set-aside status determine eligibility, and capability statements are the marketing asset."
P["Association management companies"] = "Boards select on sector experience and reference quality, which makes the client list the credential."

# --- Multi-location and network models (8) ---
P["Multi-office professional firms"] = "Offices with duplicated pages differing only by city name rank badly and convert worse."
P["Professional service franchises"] = "Franchisee recruitment and client acquisition are separate programs that should not share a budget."
P["Advisor networks"] = "Advisors join for support and lead flow, so recruitment marketing is aimed at practitioners rather than clients."
P["Broker networks"] = "Member recruitment and end-client demand are different programs with different buyers."
P["Partner-led firms"] = "Business development depends on a few partners, and individual profiles are the highest converting pages on the site."
P["Private equity-backed professional services"] = "Reporting requirements demand attribution rigour that long sales cycles make genuinely difficult."
P["National professional service platforms"] = "Consistency of service across regions is the promise, and inconsistent local data undermines it immediately."
P["Regional professional service groups"] = "Local market knowledge is the differentiator against national firms, and it has to be evidenced locally."
