# -*- coding: utf-8 -*-
"""DTC: 115 industries. One concrete marketing fact each."""

DT = {}

# --- Beauty and personal care (11) ---
DT["Skincare brands"] = "Results imagery is restricted on the platforms that drive the category, so ingredient specificity and routine become the creative."
DT["Cosmetics brands"] = "Shade matching drives returns, and virtual try-on or detailed shade guidance moves conversion more than any ad change."
DT["Haircare brands"] = "Hair type segmentation is how customers self-select, and brands that build the site around it convert better than ones organised by product line."
DT["Fragrance brands"] = "The product cannot be sampled online, which makes discovery sets the acquisition offer and the full bottle the actual margin."
DT["Mens grooming brands"] = "Subscription and replenishment carry the economics, because first order margin rarely covers acquisition in this category."
DT["Oral care brands"] = "Whitening and abrasion claims are regulated, and clinical comparison requires substantiation that most brands do not hold."
DT["Bath and body brands"] = "A gifting-heavy category where fourth quarter concentration makes annual planning misleading."
DT["Nail care brands"] = "Creator content drives the category almost entirely, because application technique is the product demonstration."
DT["Beauty device brands"] = "High ticket with a long consideration window, where financing and a return guarantee do more than discounting."
DT["Clean beauty brands"] = "Ingredient claims attract scrutiny and vague natural language is a growing enforcement target."
DT["Professional beauty brands"] = "Selling to salons and to consumers at once creates channel conflict that has to be priced deliberately."

# --- Health and wellness (15) ---
DT["Supplement brands"] = "The third order decides the business, and brands that do not know their ninety day repeat rate cannot set an acquisition target."
DT["Vitamin brands"] = "Commoditised by retail and marketplace pricing, so third party testing certification is the credible differentiator."
DT["Functional medicine products"] = "Practitioner channel and direct sales need different pricing, and running them together undercuts the practitioners."
DT["Womens health brands"] = "Platform restrictions on some health topics are severe, which pushes reach toward organic search and creator content."
DT["Mens health brands"] = "Telehealth prescribing rules vary by jurisdiction and determine where the product can even be advertised."
DT["Sexual wellness brands"] = "Advertising restrictions are the tightest in consumer goods, making email, search and creator content the viable channels."
DT["Sleep brands"] = "Sleep claims sit close to the drug claim boundary and crossing it is the most common ad rejection in the category."
DT["Stress and anxiety brands"] = "Mental health claims are restricted on every major platform, so the compliant position describes the ingredient rather than the effect."
DT["Fitness supplement brands"] = "Third party testing for banned substances is what informed buyers filter on, and it is worth leading with."
DT["Hydration brands"] = "Low ticket with heavy shipping cost, which makes multipack pricing and subscription the only route to viable margin."
DT["Weight management brands"] = "The most restricted advertising category in consumer health, where before and after imagery is prohibited outright."
DT["Longevity brands"] = "Evidence quality is what buyers in this category compare, and vague optimisation language loses to published studies."
DT["Recovery brands"] = "Athlete and creator partnerships carry credibility that paid advertising cannot buy in this category."
DT["Mobility products"] = "An older buyer or their adult child, which changes both the creative and the platform mix entirely."
DT["First aid brands"] = "Demand is event driven and unpredictable, which makes standing search presence more valuable than campaign timing."

# --- Food and beverage (14) ---
DT["Food brands"] = "Shipping perishable goods destroys contribution margin, and the pack size that makes the maths work is usually larger than customers want."
DT["Beverage brands"] = "Weight and volume make shipping economics brutal, which is why most successful beverage brands end up in retail."
DT["Snack brands"] = "Impulse driven with low order value, so bundles and subscriptions are the only path to a viable acquisition cost."
DT["Coffee brands"] = "Genuine subscription economics with a predictable consumption cycle, which makes replenishment timing the main revenue lever."
DT["Tea brands"] = "Lower consumption frequency than coffee, which lengthens the repeat cycle and changes the retention model."
DT["Functional beverage brands"] = "Health claims on beverages are regulated tightly and enforcement has increased sharply."
DT["Meal replacement brands"] = "Nutritional claims require substantiation and weight management language triggers additional restrictions."
DT["Protein brands"] = "Flavour is the repeat purchase driver, so sample packs are an acquisition tool rather than a promotion."
DT["Plant-based food brands"] = "Comparison against conventional products invites both regulatory and competitive scrutiny of the claims."
DT["Specialty diet brands"] = "Certification such as gluten free or kosher is what buyers filter on and it belongs in the product feed."
DT["Sauce and condiment brands"] = "Low order value with high shipping weight, which makes retail distribution the realistic growth path."
DT["Frozen food brands"] = "Cold chain shipping cost is the constraint that decides whether direct sale is even possible."
DT["Pet food brands"] = "Subscription economics are strong and veterinary claims are regulated, which shapes both the model and the copy."
DT["Alcohol alternative brands"] = "Advertising restrictions on adjacent alcohol categories apply inconsistently across platforms and cause unexpected rejections."

# --- Fashion and accessories (13) ---
DT["Apparel brands"] = "Return rates are high enough that gross revenue and net revenue are meaningfully different, and optimising to the wrong one loses money."
DT["Athleisure brands"] = "Fit and fabric are the repeat purchase drivers, and reviews that mention both do more than product photography."
DT["Footwear brands"] = "Sizing uncertainty is the conversion blocker, and detailed measurement guidance reduces both hesitation and returns."
DT["Jewelry brands"] = "High consideration with a gifting peak, where certification and return policy carry the purchase decision."
DT["Watch brands"] = "Authenticity concerns dominate the research, and grey market competition undercuts authorised pricing constantly."
DT["Handbag brands"] = "Counterfeits shape buyer behaviour, so authentication and provenance are the trust content that matters."
DT["Eyewear brands"] = "Virtual try-on measurably lifts conversion and reduces returns in a category defined by fit uncertainty."
DT["Headwear brands"] = "Low ticket driving low order value, which makes bundling and cross-sell the route to viable economics."
DT["Luxury fashion brands"] = "Discounting damages brand equity permanently, so acquisition has to work at full price or not at all."
DT["Sustainable fashion brands"] = "Environmental claims are an active enforcement target, and vague sustainability language is increasingly risky."
DT["Childrens apparel brands"] = "Customers age out within two years, which makes range extension the only defence against a permanent acquisition treadmill."
DT["Workwear brands"] = "Split between individual buyers and business accounts, which need different pricing, pages and payment terms."
DT["Outdoor apparel brands"] = "Enthusiast buyers who know the technical specifications, and marketing that gets them wrong does lasting damage."

# --- Home and lifestyle (15) ---
DT["Furniture brands"] = "Delivery cost and lead time are the top abandonment causes and the easiest thing to fix that most brands avoid fixing."
DT["Home decor brands"] = "Visually driven discovery with long consideration, which makes retargeting and email carry most of the revenue."
DT["Mattress brands"] = "Trial period length is the deciding factor in a category where the product cannot be evaluated before purchase."
DT["Bedding brands"] = "Material and thread count claims are compared closely, and specificity outperforms comfort language."
DT["Kitchenware brands"] = "Gifting concentration in the fourth quarter makes annual averages misleading for planning."
DT["Cookware brands"] = "High ticket with long replacement cycles, so the acquisition has to pay back on the first order."
DT["Home organization brands"] = "Seasonal demand spikes in January that most brands under-plan for."
DT["Cleaning product brands"] = "Refill and subscription models are the economics, since single purchase margin rarely supports acquisition."
DT["Lighting brands"] = "Technical specifications and compatibility questions block purchases, and answering them on the product page removes the objection."
DT["Garden brands"] = "Sharply seasonal with regional variation in timing, which means one national campaign calendar will be wrong somewhere."
DT["DIY product brands"] = "Instructional content drives both discovery and conversion, because the buyer needs to believe they can use it."
DT["Home improvement product brands"] = "Split between trade and consumer buyers with different pricing expectations and order sizes."
DT["Candles and fragrance brands"] = "Scent cannot be conveyed online, so descriptive language and sample sets do the work photography cannot."
DT["Travel goods brands"] = "Demand tracks travel booking cycles, which means the campaign calendar follows airline demand rather than retail seasons."
DT["Luggage brands"] = "Warranty terms are the primary comparison point in a category where durability is the promise."

# --- Baby kids and family (8) ---
DT["Baby product brands"] = "Safety certification is what parents search and most brands bury it in a specifications tab."
DT["Childrens product brands"] = "Marketing to children is restricted everywhere, so all targeting and creative addresses the parent."
DT["Toys and games brands"] = "Fourth quarter concentration is extreme, and inventory decisions made in summer determine the year."
DT["Educational product brands"] = "Sold on developmental outcomes, which is a claim area that needs evidence rather than assertion."
DT["Maternity brands"] = "A customer window measured in months, which makes range extension into postpartum the only retention path."
DT["Feeding product brands"] = "Infant nutrition marketing is restricted by international codes, and enforcement here is unusually strict."
DT["Diaper brands"] = "Subscription is the natural model with a predictable size progression that should drive the flow timing."
DT["Family lifestyle brands"] = "Broad positioning makes targeting difficult, and the brands that work narrow to a specific family situation."

# --- Pet and animal (7) ---
DT["Pet product brands"] = "Owners spend like it is family, and creator content featuring real pets outperforms studio product photography."
DT["Pet supplement brands"] = "Veterinary claims are regulated separately from human supplements and the permitted language is narrower."
DT["Pet wellness brands"] = "Health claims for animals need veterinary substantiation, and platform review is stricter than most brands expect."
DT["Pet accessory brands"] = "Sizing by breed and weight is the conversion blocker, and a proper size guide fixes it."
DT["Pet technology brands"] = "Subscription revenue attached to hardware, where the hardware margin is the acquisition cost."
DT["Pet subscription brands"] = "Churn concentrates between the second and third box, which is where the retention work belongs."
DT["Equestrian brands"] = "A small, knowledgeable community where credibility with riders matters more than reach."

# --- Technology and electronics (9) ---
DT["Consumer electronics brands"] = "Specification comparison drives the research and compatibility questions block the purchase."
DT["Wearable technology brands"] = "Health claims turn a consumer device into a regulated one, a line marketing teams cross accidentally."
DT["Smart home brands"] = "Ecosystem compatibility is the first filter, and stating it plainly removes the most common objection."
DT["Audio brands"] = "Enthusiast buyers compare measurements, and marketing that avoids specifications loses credibility with them."
DT["Gaming accessory brands"] = "Creator and streamer partnerships drive the category more reliably than paid advertising."
DT["Mobile accessory brands"] = "Device compatibility is the entire product feed problem, and getting it wrong drives returns."
DT["Computer accessory brands"] = "Marketplace price competition on near-identical products makes brand and warranty the only defensible position."
DT["Health technology brands"] = "Regulatory classification determines what can be claimed, and it changes with the feature set."
DT["Connected fitness brands"] = "Hardware plus subscription, where the churn rate on the subscription decides whether the hardware discount was affordable."

# --- Sports outdoor and hobby (11) ---
DT["Fitness equipment brands"] = "High ticket with heavy shipping, where delivery and assembly clarity is the conversion factor."
DT["Sporting goods brands"] = "Seasonal by sport, which means the campaign calendar is several calendars running in parallel."
DT["Outdoor recreation brands"] = "Enthusiast credibility is the entry requirement and marketing that misuses the vocabulary is rejected immediately."
DT["Cycling brands"] = "Component compatibility is technical and specific, and getting it wrong in the feed produces returns and complaints."
DT["Golf brands"] = "Equipment cycles follow annual product releases, and the used market suppresses new product pricing."
DT["Fishing brands"] = "Regional and species specific, which makes broad national campaigns wasteful compared with targeted ones."
DT["Hunting accessory brands"] = "Advertising restrictions on firearms-adjacent products are inconsistent across platforms and cause unexpected rejections."
DT["Motorcycle accessory brands"] = "Fitment by make and model is the whole catalogue problem, and search has to support it."
DT["Automotive accessory brands"] = "Vehicle fitment data drives both search and returns, and an inaccurate feed is expensive."
DT["Arts and crafts brands"] = "Tutorial content is the acquisition channel because the buyer needs to see the project before buying materials."
DT["Collectibles brands"] = "Scarcity and drop mechanics drive demand, and the email list is the entire launch channel."

# --- Commerce models (12) ---
DT["Shopify brands"] = "App accumulation slows stores over time, and an app audit is usually the fastest available speed and conversion win."
DT["Amazon brands"] = "The listing is the conversion rate, and advertising cannot rescue a listing that does not convert."
DT["Subscription brands"] = "Churn between the second and third order is where the model is decided, not at acquisition."
DT["Marketplace-first brands"] = "Platform dependency limits the customer relationship, which makes building an owned channel a strategic priority rather than a marketing one."
DT["Retail-to-DTC brands"] = "Channel conflict with retail partners is a pricing decision that has to be made before the direct channel launches."
DT["Omnichannel consumer brands"] = "Direct advertising drives retail sales it never gets credit for, and geographic testing is the only way to size it."
DT["Crowdfunded product brands"] = "Backer momentum does not transfer to ongoing acquisition, and most brands discover that after the campaign ends."
DT["International DTC brands"] = "Duty, returns and currency decide whether a market is viable, and most expansions are modelled after launch rather than before."
DT["Private equity-backed consumer brands"] = "Reporting requirements demand attribution rigour that platform numbers cannot support."
DT["Multi-brand ecommerce groups"] = "Shared acquisition infrastructure across brands is the efficiency, and shared creative rarely is."
DT["Creator-led brands"] = "Audience concentration in one person is the growth engine and the concentration risk at the same time."
DT["Wholesale-to-DTC brands"] = "Existing retail relationships constrain direct pricing, and breaking that constraint costs distribution."
