# -*- coding: utf-8 -*-
"""Trades: 129 industries. One concrete marketing fact each."""

T = {}

# --- Mechanical and building systems (17) ---
T["HVAC contractors"] = "Demand swings with the weather and the cheapest leads arrive in the shoulder weeks when competitors pause their campaigns."
T["Commercial HVAC contractors"] = "Facility managers buy on response time and service agreements, so the site has to prove uptime rather than sell installations."
T["Residential HVAC contractors"] = "Emergency replacement is captured in search within the hour, while planned replacement is won months earlier through maintenance relationships."
T["Air conditioning contractors"] = "The first hot week of the year produces more demand than the following month, and campaigns that ramp after it starts arrive late."
T["Heating contractors"] = "The first cold snap sets the season, and contractors already visible when it hits capture volume the rest of the winter."
T["Boiler contractors"] = "Older housing stock defines the market, so geographic targeting by neighbourhood age outperforms broad city targeting."
T["Furnace contractors"] = "Replacement decisions are made under pressure with a dead unit, which makes same-day availability the entire message."
T["Heat pump contractors"] = "Rebate amounts drive the market and change without much notice, so publishing current incentives accurately wins the enquiry."
T["Geothermal contractors"] = "Long sales cycles and high ticket, where the payback calculation is the content that moves people from research to quote."
T["Refrigeration contractors"] = "Commercial clients with food safety exposure buy on emergency response time above everything else."
T["Mechanical contractors"] = "Won through bid lists and general contractor relationships, so the portfolio matters more than any advertising."
T["Building automation contractors"] = "Sold to facility teams on energy savings with a payback period, which is a spreadsheet argument not a brand one."
T["Controls contractors"] = "Specified by engineers during design, so the audience is the consulting engineer rather than the building owner."
T["Fire protection contractors"] = "Inspection and compliance deadlines create predictable recurring demand tied to code cycles."
T["Sprinkler contractors"] = "Split between new construction bids and mandated inspection work, which have completely different sales cycles."
T["Elevator contractors"] = "Service contracts are the business and installation is the entry point, so contract value over years is what an acquisition is worth."
T["Generator contractors"] = "Demand spikes after every major outage, and contractors with standing campaigns capture it while others scramble."

# --- Plumbing and water (14) ---
T["Plumbing contractors"] = "A homeowner with water coming through the ceiling calls the first credible result and never compares three quotes."
T["Commercial plumbers"] = "Property managers buy on response time and after-hours availability, and price comes third."
T["Residential plumbers"] = "Emergency work funds the business and planned work stabilises it, and the two need separate campaigns and budgets."
T["Emergency plumbers"] = "Advertising twenty four hour service and sending calls to voicemail at three in the morning is the most common avoidable waste in the trade."
T["Drain cleaning companies"] = "Price shopped aggressively, so the businesses that hold margin sell the camera inspection rather than the clearing."
T["Sewer contractors"] = "High ticket work triggered by a failure, where trenchless options are what homeowners search once they hear the price of digging."
T["Septic contractors"] = "Rural service areas with long drive times, which makes accurate geographic targeting the difference between profit and loss on a job."
T["Water treatment companies"] = "Water quality concerns drive the search, and local water report content ranks well and converts better than product pages."
T["Waterproofing contractors"] = "Demand spikes after heavy rain, and campaigns that respond within days of a storm capture disproportionate volume."
T["Well drilling contractors"] = "Rural, low search volume, and a well-built page can own the category across an entire region."
T["Backflow prevention contractors"] = "Mandated annual testing creates predictable recurring revenue tied to municipal compliance deadlines."
T["Hydronic heating contractors"] = "A specialist niche where homeowners research extensively, so technical content outperforms general heating pages."
T["Irrigation contractors"] = "Sharply seasonal with spring startup and fall shutdown as the two demand peaks worth scheduling around."
T["Pool and spa contractors"] = "Construction demand is booked a season ahead while service and maintenance is the recurring revenue underneath it."

# --- Electrical and energy (13) ---
T["Electrical contractors"] = "Panel upgrades and EV charger installs are the searches with growing volume, and most electricians have no page for either."
T["Commercial electricians"] = "Won through general contractor relationships and bid lists, where advertising supports credibility rather than generating leads."
T["Residential electricians"] = "Service calls are small tickets, so the business case is the panel upgrade and rewiring work the service call uncovers."
T["Industrial electricians"] = "Certifications and safety record are the qualifying criteria, and both belong on the site where procurement can find them."
T["Solar installers"] = "Incentive programs drive the market and change frequently, so accurate current rebate content is the strongest ranking and conversion asset."
T["EV charger installers"] = "Fast-growing search volume with low competition, where being the first local contractor with a proper page wins the category."
T["Energy efficiency contractors"] = "Grant and rebate eligibility is what homeowners actually search, and explaining the application process converts better than selling the work."
T["Lighting contractors"] = "Commercial retrofit sold on payback period, which makes the calculation the centrepiece of the page."
T["Low-voltage contractors"] = "Specified during construction by integrators and builders, so the audience is trade rather than consumer."
T["Security system installers"] = "Monitoring contracts are the revenue, and installation is the acquisition cost, which changes what a lead is worth."
T["Audio visual integrators"] = "Split between residential luxury and commercial boardroom work, which need entirely separate positioning."
T["Data cabling contractors"] = "Project driven through IT departments and general contractors, with certification standards as the filter."
T["Renewable energy contractors"] = "Policy changes reshape demand overnight, and the contractors who publish the current position capture the search."

# --- Exterior and structural (14) ---
T["Roofing contractors"] = "Storm periods bring out-of-area competitors who bid up costs and leave, so permanence and warranty are the local argument."
T["Commercial roofers"] = "Property managers buy on warranty terms and disruption management, not on price per square foot."
T["Residential roofers"] = "Insurance claim questions dominate the first conversation, and contractors who explain the process get the job."
T["Siding contractors"] = "A visual purchase researched through photos for months before anyone requests a quote."
T["Gutter contractors"] = "A low ticket add-on that becomes profitable when sold alongside roofing, so bundling belongs in the campaign structure."
T["Masonry contractors"] = "Portfolio quality is the entire sales argument, and most masonry websites have four photos."
T["Concrete contractors"] = "Seasonal with a hard weather window, which concentrates the year and makes early booking campaigns valuable."
T["Foundation repair companies"] = "Fear drives the search and the honest contractors who explain when a crack is not urgent build more trust than the ones who do not."
T["Structural repair contractors"] = "Engineer reports trigger the work, so the referral audience includes structural engineers and home inspectors."
T["Deck builders"] = "Booked a season ahead, so the campaign that fills summer runs in late winter."
T["Fence contractors"] = "Neighbour disputes and new pets drive urgent demand, and material choice is what buyers research."
T["Window and door companies"] = "High ticket with rebate programs attached, where financing availability moves more quotes than discounting."
T["Garage door companies"] = "Emergency repair funds the business and replacement carries the margin, so the repair call is the acquisition opportunity."
T["Exterior renovation companies"] = "Multi-trade projects where the ability to manage the whole exterior is the differentiator against single-trade competitors."

# --- Interior renovation and finishing (15) ---
T["General contractors"] = "Buyers compare three quotes and choose the one who explained the process clearly, not usually the cheapest."
T["Renovation contractors"] = "Research runs for months through images before anyone makes contact, which makes visual platforms the top of the funnel."
T["Kitchen remodelers"] = "The single largest discretionary home purchase most families make, researched for a year and quoted three times."
T["Bathroom remodelers"] = "Faster decisions than kitchens with a lower ticket, which makes volume and process efficiency the business model."
T["Basement renovation companies"] = "Permit and egress requirements are what homeowners search first, and answering them establishes competence."
T["Flooring contractors"] = "Material selection is the research and installation is the purchase, so product content brings the traffic."
T["Tile contractors"] = "Craft quality shown in detail photography does more than any copy about experience."
T["Painting contractors"] = "Low barrier to entry means heavy competition, and insurance, crew and process detail separate the professionals."
T["Drywall contractors"] = "Mostly business to business through builders and general contractors, where reliability beats marketing."
T["Insulation contractors"] = "Rebate programs drive residential demand, and the eligibility question is the search."
T["Cabinet makers"] = "Custom work sold through portfolio and lead time, where a realistic timeline published upfront filters buyers usefully."
T["Custom closet companies"] = "A design-led sale where the free in-home consultation is the conversion event, not the quote."
T["Millwork companies"] = "Specified by designers and architects, so the audience is trade and the portfolio is the credential."
T["Countertop companies"] = "Material and edge selection drives the research, and slab availability is what closes the sale."
T["Glass contractors"] = "Emergency board-up and planned installation are different businesses that get advertised as one."

# --- Construction and development (14) ---
T["Commercial construction companies"] = "Projects are won on bid lists and relationships, so marketing exists to make the firm credible when it is already being considered."
T["Residential construction companies"] = "Land availability and financing conditions drive volume more than any marketing decision."
T["Custom home builders"] = "A two year relationship with the client, so the portfolio and the process explanation carry the entire decision."
T["Production home builders"] = "Model home traffic and community launches are the campaign events, and inventory availability changes the message weekly."
T["Real estate developers"] = "Marketing serves pre-sales and investor confidence, which are different audiences from the eventual buyer."
T["Design-build firms"] = "The single point of accountability is the differentiator, and explaining what that removes for the client is the argument."
T["Construction management firms"] = "Sold to owners on schedule and budget control, where past project performance data is the proof."
T["Civil contractors"] = "Public tendering governs most work, and prequalification status matters more than any campaign."
T["Infrastructure contractors"] = "Government procurement cycles set the calendar and capability statements are the marketing asset."
T["Industrial construction companies"] = "Safety record and certifications are the first filter in any qualification process."
T["Institutional construction companies"] = "Public sector clients require transparent process documentation, and the portfolio has to show sector experience."
T["Tenant improvement contractors"] = "Speed and minimal disruption are what landlords and tenants buy, and both can be evidenced with real timelines."
T["Restoration construction companies"] = "Insurance relationships drive the volume, so adjusters and brokers are the audience worth marketing to."
T["Modular construction companies"] = "Educating the market is most of the job because buyers carry assumptions about quality that need addressing directly."

# --- Property services (16) ---
T["Restoration companies"] = "The first company to answer gets the job, and most of these calls arrive outside business hours."
T["Water damage restoration"] = "Response time is the entire product, and campaigns running without twenty four hour answering waste most of the budget."
T["Fire damage restoration"] = "Insurance driven with adjusters as the referral source, which makes the professional relationship worth more than consumer advertising."
T["Mold remediation companies"] = "Health claims about mold are regulated and overstating risk is both a compliance and credibility problem."
T["Disaster recovery companies"] = "Commercial contracts negotiated before an event, so the sale is preparedness rather than response."
T["Pest control companies"] = "Recurring service contracts are the business, and the one-off treatment is the acquisition cost."
T["Landscaping companies"] = "Seasonal contracts signed in early spring, so the campaign that fills the year runs in February."
T["Lawn care companies"] = "Subscription economics where retention across seasons decides profitability more than acquisition volume."
T["Tree service companies"] = "Storm events create demand spikes, and emergency removal carries margin that routine trimming does not."
T["Snow removal companies"] = "Contracts signed in autumn for the whole season, which makes a narrow selling window the entire year's revenue."
T["Cleaning companies"] = "Residential recurring service where the customer lifetime is measured in years, justifying a much higher acquisition cost than one clean."
T["Commercial cleaning companies"] = "A single contract can be worth years of revenue, which means the target cost per lead should look absurd against a residential benchmark."
T["Junk removal companies"] = "Volume driven with same-day demand, where transparent pricing beats the free estimate model most competitors use."
T["Waste management companies"] = "Commercial contracts with long terms, and the sale is compliance and reliability rather than price."
T["Property maintenance companies"] = "Property managers buy a single vendor for multiple trades, so breadth is the positioning."
T["Handyman companies"] = "Small jobs with high volume, where booking convenience and transparent hourly rates decide the call."

# --- Specialty contractors (16) ---
T["Demolition contractors"] = "Permit and disposal requirements are what buyers search, and explaining them establishes competence immediately."
T["Excavation contractors"] = "Project driven through builders and general contractors, where equipment capability is the specification."
T["Paving contractors"] = "A short seasonal window and heavy competition from transient operators, which makes local permanence the argument."
T["Asphalt contractors"] = "Commercial parking lot work is contract based while residential driveways are seasonal and price shopped."
T["Scaffolding companies"] = "Rented by project with safety certification as the qualifying requirement, so compliance documentation is the marketing."
T["Crane services"] = "Booked by capacity and reach, so the equipment list is the most important page on the site."
T["Heavy equipment contractors"] = "Project driven with utilisation as the business constraint, which makes scheduling visibility more useful than lead volume."
T["Welding and fabrication companies"] = "Certifications determine which work you can bid, and buyers filter on them before anything else."
T["Sheet metal contractors"] = "Specified through mechanical contractors, so the audience is trade rather than the building owner."
T["Sign companies"] = "Permit knowledge is the differentiator because municipal sign bylaws are what stall most projects."
T["Awning companies"] = "Seasonal residential demand alongside steady commercial work, which need separate campaigns."
T["Marine contractors"] = "Waterfront regulation and permitting expertise is the whole sale, and it is what owners search first."
T["Environmental contractors"] = "Regulatory compliance driven, where certifications and remediation track record are the qualifying criteria."
T["Asbestos abatement companies"] = "Licensed work with strict protocols, where claims about safety carry real legal weight and need care."
T["Accessibility contractors"] = "Funding programs and grants drive demand, and explaining eligibility is what the enquiry is actually about."
T["Smart home installers"] = "Competing with do-it-yourself products, so the argument is integration and support rather than the hardware."

# --- Networks and business models (10) ---
T["Multi-location trades companies"] = "Branches sharing campaigns bid against each other, and the company pays the higher price without noticing."
T["Home service franchises"] = "Franchisee recruitment and customer demand are separate programs funded from one budget, and one usually starves."
T["Construction franchises"] = "Territory availability drives the recruitment message, and earnings claims carry disclosure requirements in most jurisdictions."
T["Trade contractor networks"] = "Members join for lead flow, so the marketing promise is volume the network has to actually deliver."
T["Dealer networks"] = "Manufacturer co-op funds go unused every year because dealers do not know the rules, which is a marketing opportunity in itself."
T["Manufacturer-certified installers"] = "The certification is the differentiator and most installers never build a page for it."
T["Private equity-backed home services"] = "Roll-ups inherit inconsistent brand and business data across locations, and cleaning that up is the first real gain."
T["Roll-up home service groups"] = "Acquired businesses keep local brand equity that a rebrand can destroy, so migration has to be planned rather than announced."
T["Commercial service networks"] = "National accounts are won on consistent service level across regions, which is an operational proof rather than a marketing claim."
T["National accounts contractors"] = "Procurement led with service level agreements as the deciding factor, so the sale is documentation not advertising."
